### ISSUE TITLE
Learn didn't recognize the fork or the passed test

### ISSUE THREAD

**Issue by RKoopman** [learn-co-curriculum/sql-library-lab#14]
Tried re-forking, forking manually, as well as deleting the original copy of the lab. It passed all the tests and successfully performed a pull request.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)
Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
