### ISSUE TITLE
select_value_and_count_of_most_prolific_species

### ISSUE THREAD

**Issue by scirocco21** [learn-co-curriculum/sql-library-lab#18]
This function tests for the value and count of the most prolific species _from the first series_ only; the test expects a return value of 'human, 4'. It might be worth making that clear in the description. The most prolific species without qualification would be 'cylon, 8', using the seed data.

**Comment by maxwellbenton** [comment]
Hi @scirocco21,

Thank you for opening this issue. We've updated this lesson and incorporated changes based on your feedback.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
