### ISSUE TITLE
Geeky is Awesome link redirects to blog homepage

### ISSUE THREAD

**Issue by scarsam** [learn-co-curriculum/sql-library-lab#19]
The link provided at the bottom seems no longer active. The link now redirects to the blog homepage (https://geekyisawesome.blogspot.com/) In the previous lab the link took you to this post (https://geekyisawesome.blogspot.com/2011/03/sql-joins-tutorial.html) which might be more appropriate.

Best,
Sam

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thank you for your contribution! 💙
