### ISSUE TITLE
select_character_names_and_number_of_books_they_are_in order

### ISSUE THREAD

**Issue by sentenel** [learn-co-curriculum/sql-library-lab#20]
The test requires the results to be ordered by the number of characters and then by name, while neither the query title nor any other source indicates any ordering is necessary or prefered.

**Comment by maxwellbenton** [comment]
Hi @sentenel,

Thank you for opening this issue. We've updated this lesson and added an additional message in the test `select_character_names_and_number_of_books_they_are_in order` that indicates order and group are both needed. This should help guide future students as they solve this lab.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
