### ISSUE TITLE
Characters table should not have series_id

### ISSUE THREAD

**Issue by AngusGMorrison** [learn-co-curriculum/sql-library-lab#23]
The Readme states "The Characters table has a name, motto, and species and belong to an author and a series".

However, the tests require characters and series to be joined via character_books and books, not via characters.series_id = series.id. The Flatiron GitHub solution confirms this.

**Solution**
Change Readme to say: "The Characters table has a name, motto, and species and belong to an author".

**Comment by sgharms** [comment]
You're right! Commit b41ac28 changed the data, but not the README. Updated.
